name: net_shaper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0-133.0.dev

dependencies:
  flutter:
    sdk: flutter
  lan_scanner: ^4.0.0+1
  network_info_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
